### ISSUE TITLE
Eigenes Projekt für WSC-Plugin

### ISSUE THREAD

**Issue by Cyperghost** [DevTekDE/DiscordBot#3]
Ich würde mir wünschen, wenn das WSC-Plugin eine eigenes Projekt bekommt und keinen Ordner oder Branch.
Einfach aus dem Grund, da es unterschiedliche Programmiersprachen sind und natürlich auch um das Plugin am ende bessere zu Packen zu können.

**Comment by Nathalie0hneHerz** [comment]
Eindeutiger Zuspruch, verbessert das gesamte Projektmanagement.

**Comment by DevTek314** [comment]
Vielleicht können wir auch ein WSC-Plugin programmieren, welches sowieso eine komplette API zum Forum aufbaut, da WSC leider im Gegensatz zu anderen Foren, keine eigene mitbringt.
Andere Community würden sicherlich auch davon profitieren.

**Comment by ZargorNET** [comment]
Jo bin damit einverstanden.
[Hier gehts zum Repo](https://github.com/DevTekDE/WSC-API-Plugin)
